[versions]
composeBom = "2024.09.00"
coroutines = "1.8.1"
kotlinxSerialization = "1.7.1"
lifecycle = "2.8.5"
activityCompose = "1.9.2"
datastore = "1.1.1"

[libraries]
# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# Activity
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Lifecycle
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# DataStore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
